server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  application:
    name: demo-thread-pool
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

logging:
  level:
    com.qiubithub.javainterview.threadpool: debug
    org.springframework: info
